### ISSUE TITLE
probe-run on an Arduino Nano 33 BLE?

### ISSUE THREAD

**Issue by bryanburgers** [knurling-rs/probe-run#144]
**Describe the bug**

I'm not quite sure where to ask this, because I think it's more of a "new to embedded development" question more than anything.

I'm trying to get started programming an [Arduino Nano 33 BLE](https://store.arduino.cc/usa/nano-33-ble) in Rust. It looks like the Nano 33 is a `nRF52840_xxAA`, which seems to be a supported chipset.

I have it hooked up via USB to my Mac and I can flash to it via the Arduino IDE (first new-to-this question as I was digging around trying to understand what's going on: is that because this chip comes pre-flashed with some Arduino bootloader?)

When I do a `cargo run`, I get

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `probe-run --chip nRF52840_xxAA target/thumbv7em-none-eabi/debug/arduino-nano-test`
Error: no probe was found
```

`probe-run --list-probes` tells me that no devices were found. I can't tell if that's _expected_ or if I need to do something else or if I'm completely out in left field.

```
$ probe-run --verbose --list-probes
No devices were found.
$ probe-rs-cli list
No devices were found.
```

I remember a previous co-worker at a previous job explaining things like J-Link to me; does probe-run only work with one of those things? Or should I expect probe-run to work directly connected to the Nano's USB port? Do I need to somehow flash a different bootloader onto the device first (I've seen `avrdude` mentioned...)?

**main.rs**

```rust
#![no_std]
#![no_main]

use cortex_m::asm;
use cortex_m_rt::entry;
use rtt_target::{rprintln, rtt_init_print};
use nrf52840_hal as _;

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {
        asm::bkpt()
    }
}

#[entry]
fn main() -> ! {
    rtt_init_print!();
    rprintln!("Hello, world!");

    loop {
        asm::bkpt()
    }
}
```

**Cargo.toml**

```toml
[package]
name = "arduino-nano-test"
version = "0.1.0"
authors = ["Bryan Burgers <bryan@burgers.io>"]
edition = "2018"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6"
rtt-target = { version = "0.3", features = ["cortex-m"] }
nrf52840-hal = "0.12"
```

**config.toml**
The contents of your project's `.cargo/config.toml` file

``` toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF52840_xxAA"
rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
# target = "thumbv7em-none-eabihf"  # I think it's an hf, but also saw somewhere that hf wasn't supported and need to workaround without it, but maybe that was old news
target = "thumbv7em-none-eabi"
```

**Probe details**

``` console
$ probe-rs-cli list
No devices were found
```

**Operating System:**
macOS 11.2 (Big Sur)

```
$ uname -ap
Darwin Bryans-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64 i386
```
