### ISSUE TITLE
Flashing is very slow (15-20s for an 8KB binary)

### ISSUE THREAD

**Issue by leo60228** [knurling-rs/probe-run#268]
**Describe the bug**
Flashing is very slow, taking ~15-20s for an 8KB binary.

**To Reproduce**
Flash a binary.

**Expected and observed behavior**
I expected it to be faster.

**config.toml**
``` toml
# samd21 is a Cortex-M0 and thus thumbv6m

[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
runner = 'probe-run --chip ATSAMD21E18A'

rustflags = [

  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",

  "-C", "link-arg=-Tlink.x",
]
```

**Probe details**
``` console
[nix-shell:~/atsamd/boards/pyruler]$ probe-rs-cli list
The following devices were found:
[0]: J-Link (J-Link) (VID: 1366, PID: 0101, Serial: 000801029937, JLink)
```

**Operating System:**
Linux

**ELF file (attachment)**
[ptc_regs.zip](https://github.com/knurling-rs/probe-run/files/7294876/ptc_regs.zip)

**Additional context**
I'm flashing an ATSAMD21E18A using a J-Link EDU Mini.
