### ISSUE TITLE
probe-run asserts fails, but only with measure-stack not enabled

### ISSUE THREAD

**Issue by thejpster** [knurling-rs/probe-run#310]
**Describe the bug**
```
probe-run ./target/thumbv6m-none-eabi/release/neotron-pico-bios --chip RP2040 
(HOST) INFO  flashing program (6 pages / 24.00 KiB)
(HOST) INFO  success!
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`: `end` needs to be 4-byte-aligned', /home/jonathan/.cargo/registry/src/github.com-1ecc6299db9ec823/probe-run-0.3.2/src/canary.rs:194:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The project is git@github.com:neotron-compute/neotron-pico-bios.git, with tag `knurling_bug_report0`.

The following steps work:

```
probe-run --measure-stack ./target/thumbv6m-none-eabi/release/neotron-pico-bios --chip RP2040
(HOST) INFO  flashing program (6 pages / 24.00 KiB)
(HOST) INFO  success!
(HOST) INFO  painting 4.00 KiB of RAM for stack usage estimation
────────────────────────────────────────────────────────────────────────────────
(HOST) INFO  reading 4.00 KiB of RAM for stack usage estimation
(HOST) INFO  program has used at least 1.06/4.00 KiB (26.5%) of stack space
```

**To Reproduce**
As above.

**Expected and observed behavior**

Either both modes crash (because maybe my setup is wrong), or both modes work. Having one assert and one work is weird.

**config.toml**
The contents of your project's `.cargo/config.toml` file

``` toml
[target.thumbv6m-none-eabi]
# This will make a UF2 and copy it to the RP2040's Mass Storage Device bootloader
# runner = "elf2uf2-rs -d"
# This will flash over SWD with any compatible probe it finds. You need 0.3.1 or higher for RP2040 support.
runner = "probe-run --chip RP2040"

rustflags = [
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  "-C", "link-arg=--nmagic",

  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",

  # Support defmt formatted logging
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

```

**Probe details**

``` console
$ probe-run --list-probes
the following probes were found:
[0]: RP2040 CMSIS-DAP (VID: cafe, PID: 4005, Serial: 6E06837B3165D233, CmsisDap)

```

**Operating System:**

Arch Linux.

**ELF file (attachment)**

[neotron-pico-bios.zip](https://github.com/knurling-rs/probe-run/files/8240699/neotron-pico-bios.zip)

**Additional context**
