### ISSUE TITLE
Error: `.vector_table` section is missing

### ISSUE THREAD

**Issue by TheButlah** [knurling-rs/probe-run#350]
**Describe the bug**
Flashing firmware for ESP32-C3 fails with an error. This happens regardless of whether the `direct-boot` feature is provided to the `esp-hal` (direct-boot bypasses the second stage bootloader on the esp32c3).

Cargo flash works, although it only works in direct-boot mode due to https://github.com/probe-rs/probe-rs/issues/1194

**To Reproduce**
```
❯ probe-run --chip esp32c3 target/riscv32imac-unknown-none-elf/debug/firmware
Error: `.vector_table` section is missing
```

**Expected and observed behavior**
Expected the program to flash successfully.

**config.toml**
The contents of your project's `.cargo/config.toml` file

``` toml
[target.riscv32imac-unknown-none-elf]
# runner = "espflash --monitor"
runner = "probe-run --chip esp32c3"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",

  "-C",
  "link-arg=-Tlinkall.x",

  # For defmt
  # "-C",
  # "link-arg=-Tdefmt.x",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]
```

**Probe details**
You can get this information from [`probe-rs-cli`](https://crates.io/crates/probe-rs-cli). Your microcontroller must be connected to your PC / laptop when you run the command below.

*Example:*

``` console
❯ probe-rs-cli list
The following devices were found:
[0]: ESP JTAG (VID: 303a, PID: 1001, Serial: 84:F7:03:33:50:60, EspJtag)
❯ probe-rs-cli info
No DAP interface was found on the connected probe. Thus, ARM info cannot be printed.
RISCV Chip:
        IDCODE: 0000005c25
         Version:      0
         Part:         5
         Manufacturer: 1554 (Espressif Systems (Shanghai)  Co Ltd)
```

**Operating System:**
MacOS 12.5

**ELF file (attachment)**
[firmware.zip](https://github.com/knurling-rs/probe-run/files/9436226/firmware.zip)
